# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/enthus-appdev/atl-cli

linters:
  # Use standard defaults with minimal additions
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - misspell

  # Disable noisy linters for CLI project
  disable:
    - errcheck  # Too noisy for CLI - lots of intentional ignores

  settings:
    misspell:
      locale: US

    staticcheck:
      checks:
        - all
        - -ST1000  # Package comments not required

issues:
  exclude-rules:
    # Test files have relaxed rules
    - path: _test\.go
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
