run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - copyloopvar
    - misspell
  disable:
    - errcheck

linters-settings:
  misspell:
    locale: US
  staticcheck:
    checks:
      - all
      - -ST1000

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
