version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - copyloopvar
    - misspell
  disable:
    - errcheck
  settings:
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -ST1000
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/enthus-appdev/atl-cli
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
